#!/bin/sh
# 
# This file is part of 
# docker-nrpe-server a Dockerized version of Nagios' NRPE server 
# <https://github.com/binfalse/docker-nrpe-server>
# Copyright (C) 2017 Martin Scharm <https://binfalse.de/contact/>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

OURCONF=/etc/nagios/auto-manage.cfg

[ -e $OURCONF ] && rm $OURCONF
touch $OURCONF


# SET ALLOWED HOSTS
if [ -n "$ALLOWEDHOSTS" ]
then
    echo "allowed_hosts=$ALLOWEDHOSTS" >> $OURCONF
fi


# SET LISTENING PORT
if [ -n "$PORT" ]
then
    echo "server_port=$PORT" >> $OURCONF
else
    echo "server_port=5666" >> $OURCONF
fi

# USE SSL?
SSLFLAG=""
if [ "$SSL" = "yes" ]
then
    echo "ssl_cacert_file=/etc/nagios/certs/chain.txt" >> $OURCONF
		echo "ssl_cert_file=/etc/nagios/certs/cert.cer" >> $OURCONF
		echo "ssl_privatekey_file=/etc/nagios/certs/key.pem" >> $OURCONF
else
    SSLFLAG="-n"
fi



mkdir -p /var/run/nagios /etc/nagios/certs /usr/lib/nagios/extra
[ -e "/var/run/nagios/nrpe.pid" ] && rm "/var/run/nagios/nrpe.pid"
echo "pid_file=/var/run/nagios/nrpe.pid" >> $OURCONF

# run the fake syslog to print the log to std::out
/bin/syslog2stdout /dev/log &

# run the server
/usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -f $SSLFLAG

